var data={
    "code": 0,
    "msg": "",
    "count": 1000,
    "data": [
        {
            "id": 10000,
            "username": "user-0",
            "fileInfo": "theExample.doc",
            "fileDate": "2018-03-15",
            "fileType": "word文档",
            "fileTag": 'word',
            "logins": 24,
            "wealth": 82830700,
            "classify": "作家",
            "score": 57
        },
        {
            "id": 10001,
            "username": "user-1",
            "fileInfo": "compressed.tracemonkey-pldi-09.pdf",
            "fileDate": "2018-03-19",
            "fileType": "pdf文档",
            "fileTag": 'pdf',
            "logins": 58,
            "wealth": 64928690,
            "classify": "词人",
            "score": 27
        },
        {
            "id": 10002,
            "username": "user-2",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-19",
            "fileType": "word文档",
            "fileTag": 'word',
            "logins": 77,
            "wealth": 6298078,
            "classify": "酱油",
            "score": 31
        },
        {
            "id": 10003,
            "username": "user-3",
            "fileInfo": "代码规范.pdf",
            "fileDate": "2018-03-19",
            "fileType": "pdf文档",
            "fileTag": 'pdf',
            "logins": 157,
            "wealth": 37117017,
            "classify": "诗人",
            "score": 68
        },
        {
            "id": 10004,
            "username": "user-4",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-19",
            "fileType": "word文档",
            "fileTag": 'word',
            "logins": 51,
            "wealth": 76263262,
            "classify": "作家",
            "score": 6
        },
        {
            "id": 10005,
            "username": "user-5",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-19",
            "fileType": "word文档",
            "fileTag": 'word',
            "logins": 68,
            "wealth": 60344147,
            "classify": "作家",
            "score": 87
        },
        {
            "id": 10006,
            "username": "user-6",
            "fileInfo": "test.xlsx",
            "fileDate": "2018-03-19",
            "fileType": "excel文档",
            "fileTag": 'excel',
            "logins": 37,
            "wealth": 57768166,
            "classify": "作家",
            "score": 34
        },
        {
            "id": 10007,
            "username": "user-7",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-19",
            "fileType": "word文档",
            "fileTag": 727,
            "logins": 150,
            "wealth": 82030578,
            "classify": "作家",
            "score": 28
        },
        {
            "id": 10008,
            "username": "user-8",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-19",
            "fileType": "word文档",
            "fileTag": 951,
            "logins": 133,
            "wealth": 16503371,
            "classify": "词人",
            "score": 14
        },
        {
            "id": 10009,
            "username": "user-9",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-19",
            "fileType": "word文档",
            "fileTag": 484,
            "logins": 25,
            "wealth": 86801934,
            "classify": "词人",
            "score": 75
        },
        {
            "id": 10010,
            "username": "user-10",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-190",
            "fileType": "word文档0",
            "fileTag": 1016,
            "logins": 182,
            "wealth": 71294671,
            "classify": "诗人",
            "score": 34
        },
        {
            "id": 10011,
            "username": "user-11",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-191",
            "fileType": "word文档1",
            "fileTag": 492,
            "logins": 107,
            "wealth": 8062783,
            "classify": "诗人",
            "score": 6
        },
        {
            "id": 10012,
            "username": "user-12",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-192",
            "fileType": "word文档2",
            "fileTag": 106,
            "logins": 176,
            "wealth": 42622704,
            "classify": "词人",
            "score": 54
        },
        {
            "id": 10013,
            "username": "user-13",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-193",
            "fileType": "word文档3",
            "fileTag": 1047,
            "logins": 94,
            "wealth": 59508583,
            "classify": "诗人",
            "score": 63
        },
        {
            "id": 10014,
            "username": "user-14",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-194",
            "fileType": "word文档4",
            "fileTag": 873,
            "logins": 116,
            "wealth": 72549912,
            "classify": "词人",
            "score": 8
        },
        {
            "id": 10015,
            "username": "user-15",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-195",
            "fileType": "word文档5",
            "fileTag": 1068,
            "logins": 27,
            "wealth": 52737025,
            "classify": "作家",
            "score": 28
        },
        {
            "id": 10016,
            "username": "user-16",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-196",
            "fileType": "word文档6",
            "fileTag": 862,
            "logins": 168,
            "wealth": 37069775,
            "classify": "酱油",
            "score": 86
        },
        {
            "id": 10017,
            "username": "user-17",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-197",
            "fileType": "word文档7",
            "fileTag": 1060,
            "logins": 187,
            "wealth": 66099525,
            "classify": "作家",
            "score": 69
        },
        {
            "id": 10018,
            "username": "user-18",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-198",
            "fileType": "word文档8",
            "fileTag": 866,
            "logins": 88,
            "wealth": 81722326,
            "classify": "词人",
            "score": 74
        },
        {
            "id": 10019,
            "username": "user-19",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-199",
            "fileType": "word文档9",
            "fileTag": 682,
            "logins": 106,
            "wealth": 68647362,
            "classify": "词人",
            "score": 51
        },
        {
            "id": 10020,
            "username": "user-20",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-190",
            "fileType": "word文档0",
            "fileTag": 770,
            "logins": 24,
            "wealth": 92420248,
            "classify": "诗人",
            "score": 87
        },
        {
            "id": 10021,
            "username": "user-21",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-191",
            "fileType": "word文档1",
            "fileTag": 184,
            "logins": 131,
            "wealth": 71566045,
            "classify": "词人",
            "score": 99
        },
        {
            "id": 10022,
            "username": "user-22",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-192",
            "fileType": "word文档2",
            "fileTag": 739,
            "logins": 152,
            "wealth": 60907929,
            "classify": "作家",
            "score": 18
        },
        {
            "id": 10023,
            "username": "user-23",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-193",
            "fileType": "word文档3",
            "fileTag": 127,
            "logins": 82,
            "wealth": 14765943,
            "classify": "作家",
            "score": 30
        },
        {
            "id": 10024,
            "username": "user-24",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-194",
            "fileType": "word文档4",
            "fileTag": 212,
            "logins": 133,
            "wealth": 59011052,
            "classify": "词人",
            "score": 76
        },
        {
            "id": 10025,
            "username": "user-25",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-195",
            "fileType": "word文档5",
            "fileTag": 938,
            "logins": 182,
            "wealth": 91183097,
            "classify": "作家",
            "score": 69
        },
        {
            "id": 10026,
            "username": "user-26",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-196",
            "fileType": "word文档6",
            "fileTag": 978,
            "logins": 7,
            "wealth": 48008413,
            "classify": "作家",
            "score": 65
        },
        {
            "id": 10027,
            "username": "user-27",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-197",
            "fileType": "word文档7",
            "fileTag": 371,
            "logins": 44,
            "wealth": 64419691,
            "classify": "诗人",
            "score": 60
        },
        {
            "id": 10028,
            "username": "user-28",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-198",
            "fileType": "word文档8",
            "fileTag": 977,
            "logins": 21,
            "wealth": 75935022,
            "classify": "作家",
            "score": 37
        },
        {
            "id": 10029,
            "username": "user-29",
            "fileInfo": "example.doc",
            "fileDate": "2018-03-199",
            "fileType": "word文档9",
            "fileTag": 647,
            "logins": 107,
            "wealth": 97450636,
            "classify": "酱油",
            "score": 27
        }
    ]
}
